apiVersion: apps/v1
kind: Deployment
metadata:
  name: microserviciojava-deployment
  labels:
    app: microservicio-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio-java
  template:
    metadata:
      labels:
        app: microservicio-java
    spec:
      containers:
      - name: microservicio-java
        image: dockeruser701/useruoh:latest
        ports:
        - containerPort: 8080
